# General information of this device: brand, models available and working frequency
brand : "Universal Robots"
models:
  UR3:
    description: "Robot manipulator arm with 6-DOF and 500 mm length."
  UR5:
    description: "Robot manipulator arm with 6-DOF and 850 mm length."
  UR10:
    description: "Robot manipulator arm with 6-DOF and 1300 mm length."
frequency : 125
is_manipulator: true

moveit_control: false

sockets:
  port_in    : '30002'
  port_out   : '30003'
  tcp_30002:
    move_joints:
      request : [ "movej([", "q1", ", ", "q2", ", ", "q3", ", ", "q4", ", ", "q5", ", ", "q6", "], a=4.5, v=0.5)", "\n" ]
      q1      : ["String", 1]
      q2      : ["String", 1]
      q3      : ["String", 1]
      q4      : ["String", 1]
      q5      : ["String", 1]
      q6      : ["String", 1]
    move_pose:
      request : [ "movel(p[", "px", ", ", "py", ", ", "pz", ", ", "rx", ", ", "ry", ", ", "rz", "], a=4.5, v=0.5)", "\n" ]
      px      : ["String", 1]
      py      : ["String", 1]
      pz      : ["String", 1]
      rx      : ["String", 1]
      ry      : ["String", 1]
      rz      : ["String", 1]
    speed_joints:
      request : [ "speedj([", "q1", ", ", "q2", ", ", "q3", ", ", "q4", ", ", "q5", ", ", "q6", "], a=4.5, t=0.04)", "\n" ]
      q1     : ["String", 1]
      q2     : ["String", 1]
      q3     : ["String", 1]
      q4     : ["String", 1]
      q5     : ["String", 1]
      q6     : ["String", 1]
    speed_pose:
      request : [ "speedl([", "px", ", ", "py", ", ", "pz", ", ", "rx", ", ", "ry", ", ", "rz", "], a=4.5, t=0.04)", "\n" ]
      px      : ["String", 1]
      py      : ["String", 1]
      pz      : ["String", 1]
      rx      : ["String", 1]
      ry      : ["String", 1]
      rz      : ["String", 1]
    set_freedrive:
      request : [ "set robotmode freedrive", "\n" ]
    set_run:
      request : [ "set robotmode run", "\n" ]
  tcp_30003:
    reading_3.0:
      response       : [ "size", "time", "q_target", "qd_target", "qdd_target", "i_target", "m_target", "q_actual", "qd_actual", "i_actual", "i_control", "pose_actual", "speed_actual", "force_actual", "pose_target", "speed_target", "digital_in", "t_actual", "time_control", "test_value", "mode_robot", "mode_joint", "mode_safety", "test_vector", "accel_actual", "test_vector", "speed_scale", "linear_momentum", "test_value", "test_value", "v_main", "v_robot", "i_robot", "v_actual" ]
      size           : ["Integer[1]", 4]
      time           : ["Double[1]", 8]
      q_target       : ["Double[6]", 8]
      qd_target      : ["Double[6]", 8]
      qdd_target     : ["Double[6]", 8]
      i_target       : ["Double[6]", 8]
      m_target       : ["Double[6]", 8]
      q_actual       : ["Double[6]", 8]
      qd_actual      : ["Double[6]", 8]
      i_actual       : ["Double[6]", 8]
      i_control      : ["Double[6]", 8]
      pose_actual    : ["Double[6]", 8]
      speed_actual   : ["Double[6]", 8]
      force_actual   : ["Double[6]", 8]
      pose_target    : ["Double[6]", 8]
      speed_target   : ["Double[6]", 8]
      digital_in     : ["Double[1]", 8]
      t_actual       : ["Double[6]", 8]
      time_control   : ["Double[1]", 8]
      test_value     : ["Double[1]", 8]
      mode_robot     : ["Double[1]", 8]
      mode_joint     : ["Double[6]", 8]
      mode_safety    : ["Double[1]", 8]
      test_vector    : ["Double[6]", 8]
      accel_actual   : ["Double[3]", 8]
      speed_scale    : ["Double[1]", 8]
      linear_momentum: ["Double[1]", 8]
      v_main         : ["Double[1]", 8]
      v_robot        : ["Double[1]", 8]
      i_robot        : ["Double[1]", 8]
      v_actual       : ["Double[6]", 8]
    reading_3.2:
      response       : [ "size", "time", "q_target", "qd_target", "qdd_target", "i_target", "m_target", "q_actual", "qd_actual", "i_actual", "i_control", "pose_actual", "speed_actual", "force_actual", "pose_target", "speed_target", "digital_in", "t_actual", "time_control", "test_value", "mode_robot", "mode_joint", "mode_safety", "test_vector", "accel_actual", "test_vector", "speed_scale", "linear_momentum", "test_value", "test_value", "v_main", "v_robot", "i_robot", "v_actual", "digital_out", "state" ]
      size           : ["Integer[1]", 4]
      time           : ["Double[1]", 8]
      q_target       : ["Double[6]", 8]
      qd_target      : ["Double[6]", 8]
      qdd_target     : ["Double[6]", 8]
      i_target       : ["Double[6]", 8]
      m_target       : ["Double[6]", 8]
      q_actual       : ["Double[6]", 8]
      qd_actual      : ["Double[6]", 8]
      i_actual       : ["Double[6]", 8]
      i_control      : ["Double[6]", 8]
      pose_actual    : ["Double[6]", 8]
      speed_actual   : ["Double[6]", 8]
      force_actual   : ["Double[6]", 8]
      pose_target    : ["Double[6]", 8]
      speed_target   : ["Double[6]", 8]
      digital_in     : ["Double[1]", 8]
      t_actual       : ["Double[6]", 8]
      time_control   : ["Double[1]", 8]
      test_value     : ["Double[1]", 8]
      mode_robot     : ["Double[1]", 8]
      mode_joint     : ["Double[6]", 8]
      mode_safety    : ["Double[1]", 8]
      test_vector    : ["Double[6]", 8]
      accel_actual   : ["Double[3]", 8]
      speed_scale    : ["Double[1]", 8]
      linear_momentum: ["Double[1]", 8]
      v_main         : ["Double[1]", 8]
      v_robot        : ["Double[1]", 8]
      i_robot        : ["Double[1]", 8]
      v_actual       : ["Double[6]", 8]
      digital_out    : ["Double[1]", 8]
      state          : ["Double[1]", 8]
    reading_3.5:
      response       : [ "size", "time", "q_target", "qd_target", "qdd_target", "i_target", "m_target", "q_actual", "qd_actual", "i_actual", "i_control", "pose_actual", "speed_actual", "force_actual", "pose_target", "speed_target", "digital_in", "t_actual", "time_control", "test_value", "mode_robot", "mode_joint", "mode_safety", "test_vector", "accel_actual", "test_vector", "speed_scale", "linear_momentum", "test_value", "test_value", "v_main", "v_robot", "i_robot", "v_actual", "digital_out", "state", "pose_elbow", "speed_elbow" ]
      size           : ["Integer[1]", 4]
      time           : ["Double[1]", 8]
      q_target       : ["Double[6]", 8]
      qd_target      : ["Double[6]", 8]
      qdd_target     : ["Double[6]", 8]
      i_target       : ["Double[6]", 8]
      m_target       : ["Double[6]", 8]
      q_actual       : ["Double[6]", 8]
      qd_actual      : ["Double[6]", 8]
      i_actual       : ["Double[6]", 8]
      i_control      : ["Double[6]", 8]
      pose_actual    : ["Double[6]", 8]
      speed_actual   : ["Double[6]", 8]
      force_actual   : ["Double[6]", 8]
      pose_target    : ["Double[6]", 8]
      speed_target   : ["Double[6]", 8]
      digital_in     : ["Double[1]", 8]
      t_actual       : ["Double[6]", 8]
      time_control   : ["Double[1]", 8]
      test_value     : ["Double[1]", 8]
      mode_robot     : ["Double[1]", 8]
      mode_joint     : ["Double[6]", 8]
      mode_safety    : ["Double[1]", 8]
      test_vector    : ["Double[6]", 8]
      accel_actual   : ["Double[3]", 8]
      speed_scale    : ["Double[1]", 8]
      linear_momentum: ["Double[1]", 8]
      v_main         : ["Double[1]", 8]
      v_robot        : ["Double[1]", 8]
      i_robot        : ["Double[1]", 8]
      v_actual       : ["Double[6]", 8]
      digital_out    : ["Double[1]", 8]
      state          : ["Double[1]", 8]
      pose_elbow     : ["Double[3]", 8]
      speed_elbow    : ["Double[3]", 8]

