controller_list:
  - name: fake_arm_controller
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
  - name: fake_ftsensor_controller
    joints:
      []